# Generated by Django 5.1.5 on 2025-02-11 19:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='asignado_a',
        ),
        migrations.AddField(
            model_name='cliente',
            name='asignado_a',
            field=models.ManyToManyField(blank=True, related_name='clientes_asignados', to=settings.AUTH_USER_MODEL),
        ),
    ]
