# Generated by Django 5.1.5 on 2025-02-18 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0002_remove_cliente_asignado_a_cliente_asignado_a'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Sector',
                'verbose_name_plural': 'Sectores',
                'ordering': ['descripcion'],
            },
        ),
    ]
