# Generated by Django 5.1.5 on 2025-02-18 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0003_sector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='sector',
            field=models.ForeignKey(help_text='Sector o industria', on_delete=django.db.models.deletion.PROTECT, to='appone.sector'),
        ),
    ]
