# Generated by Django 5.1.5 on 2025-02-18 21:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0004_alter_cliente_sector'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioLicitacionPrioridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_licitacion', models.CharField(max_length=255)),
                ('prioridad', models.BooleanField()),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licitaciones_priorizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Prioridad de Licitación por Usuario',
                'verbose_name_plural': 'Prioridades de Licitaciones por Usuario',
                'unique_together': {('usuario', 'codigo_licitacion')},
            },
        ),
    ]
