# Generated by Django 5.1.5 on 2025-02-18 22:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0005_usuariolicitacionprioridad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='licitacionclasificadacategoria',
            name='licitacion_clasificada',
        ),
        migrations.RemoveField(
            model_name='licitacionclasificadaarchivo',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='licitacionclasificadaarchivo',
            name='licitacion_diaria',
        ),
        migrations.RemoveField(
            model_name='licitacionclasificadacategoriaarchivo',
            name='licitacion_clasificada',
        ),
        migrations.RemoveField(
            model_name='licitacionclasificadacategoria',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='licitacionclasificadacategoriaarchivo',
            name='categoria',
        ),
        migrations.AddField(
            model_name='usuariolicitacionprioridad',
            name='estado_proceso',
            field=models.CharField(default='completado', help_text="Estado del proceso de priorización (por ejemplo, 'pendiente', 'completado', 'error')", max_length=50),
        ),
        migrations.AddField(
            model_name='usuariolicitacionprioridad',
            name='perfil_utilizado',
            field=models.JSONField(blank=True, help_text='Datos del perfil utilizados en la priorización (en formato JSON)', null=True),
        ),
        migrations.AddField(
            model_name='usuariolicitacionprioridad',
            name='run_id',
            field=models.CharField(blank=True, help_text='Identificador del proceso de priorización', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usuariolicitacionprioridad',
            name='tiempo_ejecucion',
            field=models.DurationField(blank=True, help_text='Tiempo de ejecución del proceso de priorización', null=True),
        ),
        migrations.CreateModel(
            name='UsuarioLicitacionPrioridadArchivado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_licitacion', models.CharField(max_length=255)),
                ('prioridad', models.BooleanField()),
                ('fecha_archivado', models.DateTimeField(auto_now_add=True)),
                ('run_id', models.CharField(blank=True, help_text='Identificador del proceso de priorización', max_length=100, null=True)),
                ('tiempo_ejecucion', models.DurationField(blank=True, help_text='Tiempo de ejecución del proceso de priorización', null=True)),
                ('perfil_utilizado', models.JSONField(blank=True, help_text='Datos del perfil utilizados en la priorización (en formato JSON)', null=True)),
                ('estado_proceso', models.CharField(default='completado', help_text="Estado del proceso de priorización (por ejemplo, 'pendiente', 'completado', 'error')", max_length=50)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licitaciones_priorizadas_archivadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Prioridad Archivada de Licitación por Usuario',
                'verbose_name_plural': 'Prioridades Archivadas de Licitaciones por Usuario',
                'unique_together': {('usuario', 'codigo_licitacion', 'fecha_archivado')},
            },
        ),
        migrations.DeleteModel(
            name='LicitacionClasificada',
        ),
        migrations.DeleteModel(
            name='LicitacionClasificadaArchivo',
        ),
        migrations.DeleteModel(
            name='LicitacionClasificadaCategoria',
        ),
        migrations.DeleteModel(
            name='LicitacionClasificadaCategoriaArchivo',
        ),
    ]
