# Generated by Django 5.1.5 on 2025-02-24 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0006_remove_licitacionclasificadacategoria_licitacion_clasificada_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PalabrasClaveUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords_usuario', models.CharField(help_text='Ingresa múltiples palabras clave separadas por comas. (Máx. 255 caracteres)', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='palabras_clave_usuario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
