# Generated by Django 5.1.5 on 2025-02-25 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0007_palabrasclaveusuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='sector',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='palabrasclaveusuario',
            name='keywords_usuario',
            field=models.CharField(help_text='Ingresa múltiples palabras clave separadas por comas. (Máx. 100 caracteres)', max_length=100),
        ),
    ]
