# Generated by Django 5.1.5 on 2025-02-25 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0008_sector_creado_por_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sector',
            name='creado_por',
        ),
    ]
