# Generated by Django 5.1.5 on 2025-03-04 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0009_remove_sector_creado_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Formato: +1234567890', max_length=20, null=True),
        ),
    ]
